security:

    encoders:
        WsbPozBundle\Entity\User:
            algorithm: bcrypt


    providers:
        in_memory:
            memory: ~

        user_provider:
            entity:
                class: WsbPozBundle:User
                property: username


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false


        default:
            pattern: ^/
            anonymous: ~
            provider: user_provider

            form_login:
                login_path:  /login
                check_path:  /login_check

            logout:
                path: /logout
                target: /
                invalidate_session: true


    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/, roles: ROLE_ADMIN }
